### ISSUE TITLE
Cant build OCATS from parent project structure

### ISSUE THREAD

**Issue by sajayjk** [Comcast/cats#14]
Getting the following error:

Build Steps & failed:
[one@localhost cats]$ cd superpom/
[one@localhost superpom]$ mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building OCATS Super POM 1.1-OCATS-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ superpom-ocats ---
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ superpom-ocats ---
[INFO] Installing /home/one/opensource/cats/superpom/pom.xml to /home/one/.m2/repository/com/comcast/cats/superpom-ocats/1.1-OCATS-SNAPSHOT/superpom-ocats-1.1-OCATS-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.461s
[INFO] Finished at: Fri Sep 18 11:39:19 EDT 2015
[INFO] Final Memory: 6M/145M
[INFO] ------------------------------------------------------------------------
[one@localhost superpom]$ cd ..
[one@localhost cats]$ mvn clean install
[INFO] Scanning for projects...
Downloading: http://repo.maven.apache.org/maven2/com/comcast/cats/superpom-ocats/1.0-OCATS/superpom-ocats-1.0-OCATS.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.comcast.cats:ocats-project:1.1-OCATS-SNAPSHOT (/home/one/opensource/cats/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact com.comcast.cats:superpom-ocats:pom:1.0-OCATS in central (http://repo.maven.apache.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 30, column 10 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
[one@localhost cats]$

**Comment by sajayjk** [comment]
Please use the a released version of OCATS. Currently I guess you checked out of the development branch. 

https://github.com/Comcast/cats/releases/tag/v1.0

**Comment by mgia1170** [comment]
I tried to build with cats v1.0, but still failed as:
[one@localhost cats-1.0]$ cd superpom/
[one@localhost superpom]$ mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building OCATS Super POM 1.1-OCATS-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ superpom-ocats ---
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ superpom-ocats ---
[INFO] Installing /home/one/opensource/cats1/cats-1.0/superpom/pom.xml to /home/one/.m2/repository/com/comcast/cats/superpom-ocats/1.1-OCATS-SNAPSHOT/superpom-ocats-1.1-OCATS-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.445s
[INFO] Finished at: Fri Sep 18 13:31:55 EDT 2015
[INFO] Final Memory: 6M/145M
[INFO] ------------------------------------------------------------------------

[one@localhost cats-1.0]$ mvn -e clean install
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM: Failure to find com.comcast.cats:superpom-ocats:pom:1.0-OCATS in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 30, column 10

        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:364)
        at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:638)
        at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:587)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:230)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:153)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
[ERROR]
[ERROR]   The project com.comcast.cats:ocats-project:1.1-OCATS-SNAPSHOT (/home/one/opensource/cats1/cats-1.0/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find com.comcast.cats:superpom-ocats:pom:1.0-OCATS in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 30, column 10 -> [Help 2]
org.apache.maven.model.resolution.UnresolvableModelException: Failure to find com.comcast.cats:superpom-ocats:pom:1.0-OCATS in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
        at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:159)
        at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:817)
        at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:669)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:307)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:411)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:380)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:344)
        at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:638)
        at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:587)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:230)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:153)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find com.comcast.cats:superpom-ocats:pom:1.0-OCATS in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:459)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:262)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:239)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:295)
        at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:155)
        ... 21 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find com.comcast.cats:superpom-ocats:pom:1.0-OCATS in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:232)
        at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:599)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:518)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:436)
        ... 25 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
[one@localhost cats-1.0]$

**Comment by sajayjk** [comment]
There seems to be an error in the release. 
We shall fix it soon.

In the meantime, please build he superpom and modify the pom in the root folder to depend on version 1.1-OCATS-SNAPSHOT of the superpom.

The updated pom will look like this:

    <parent>
		<groupId>com.comcast.cats</groupId>
		<artifactId>superpom-ocats</artifactId>
		<version>1.1-OCATS-SNAPSHOT</version>
	</parent>

**Comment by NazeeyaBanu** [comment]
I am still facing this issue - Not able to build from root. 
Any fix is available ?
