### ISSUE TITLE
StringIndexOutOfBoundsException in video recorder UI

### ISSUE THREAD

**Issue by XsubinX** [Comcast/cats#30]
### Error

JBoss is throwing StringIndexOutOfBoundsException while accessing video recorder UI  http://127.0.0.1:8080/video-recorder-service/

```
18:25:32,452 SEVERE [javax.enterprise.resource.webcontainer.jsf.application] (http--127.0.0.1-8080-13) Error Rendering View[/record/new.xhtml]: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658) [rt.jar:1.7.0_79]
	at com.sun.faces.application.view.MultiViewHandler.getResourceURL(MultiViewHandler.java:335) [jsf-impl-2.1.7-jbossorg-2.jar:]
	at javax.faces.application.ViewHandlerWrapper.getResourceURL(ViewHandlerWrapper.java:244) [jboss-jsf-api_2.1_spec-2.0.1.Final.jar:2.0.1.Final]
```

### Root Cause

Empty URL in https://github.com/Comcast/cats/blob/master/services/video-recorder/war/src/main/webapp/template.xhtml

```
<p:submenu label="Help">
						<p:menuitem value="About" oncomplete="aboutDlg.show();" />
						<p:menuitem value="WSDL" url="/VideoRecorderService?wsdl"
							target="_blank" />
						<p:menuitem value="Wiki"
							url=""
							target="_blank" />
						<p:menuitem value="Support"
							url=""
							target="_blank" />
					</p:submenu>
```

### Fix

Remove **Wiki** and **Support** Links

```
<p:submenu label="Help">
						<p:menuitem value="About" oncomplete="aboutDlg.show();" />
						<p:menuitem value="WSDL" url="/VideoRecorderService?wsdl"
							target="_blank" />
					</p:submenu>
```

**Comment by LTComcast** [comment]
Hello Subin,

Thanks a lot for your support!!

Now we are able to see the UI page of video-recorder-service successfully. PFA for the UI of the same.

![video-recorder-service](https://cloud.githubusercontent.com/assets/19969537/17016609/80b6414e-4f4d-11e6-9854-50c14a274c3e.png)
