### ISSUE TITLE
Issue while deploying Video recoder service and OCATS war files

### ISSUE THREAD

**Issue by sjsauto** [Comcast/cats#34]
I am getting the below error while deploying video-recorder-service.war and OCATS.war.  I have attached my standalone-full.xml and server.log file.  please let me know if you need any further information. 

Below are the datasource and the deployment snapshot. 
![datasource](https://cloud.githubusercontent.com/assets/22946767/19540828/f0c8e6f2-9616-11e6-915a-8e56630822f4.png)
![deployment](https://cloud.githubusercontent.com/assets/22946767/19540827/f0c70828-9616-11e6-9b9a-cbebf65a9bb8.PNG)

Request your help in fixing this.

5:45:14,972 ERROR [org.jboss.as](Controller Boot Thread) JBAS015875: JBoss AS 7.1.1.Final "Brontes" started (with errors) in 23408ms - Started 286 of 380 services (4 services failed or missing dependencies, 88 services are passive or on-demand)
15:47:59,139 INFO  [org.jboss.as.server.deployment](MSC service thread 1-2) JBAS015876: Starting deployment of "OCATS.war"
[standalone-full.xml.txt](https://github.com/Comcast/cats/files/540445/standalone-full.xml.txt)
[server.log.txt](https://github.com/Comcast/cats/files/540448/server.log.txt)

15:48:00,311 ERROR [org.jboss.msc.service.fail](MSC service thread 1-1) MSC00001: Failed to start service jboss.deployment.unit."OCATS.war".POST_MODULE: org.jboss.msc.service.StartException in service jboss.deployment.unit."OCATS.war".POST_MODULE: Failed to process phase POST_MODULE of deployment "OCATS.war"
    at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:119) [jboss-as-server-7.1.1.Final.jar:7.1.1.Final]
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_79]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_79]
    at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_79]
Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: Could not load EJB class com.comcast.cats.config.ui.monitoring.reboot.UpTimeMonitor
    at org.jboss.as.ejb3.deployment.processors.BusinessViewAnnotationProcessor.getEjbClass(BusinessViewAnnotationProcessor.java:227)
    at org.jboss.as.ejb3.deployment.processors.BusinessViewAnnotationProcessor.deploy(BusinessViewAnnotationProcessor.java:97)
    at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:113) [jboss-as-server-7.1.1.Final.jar:7.1.1.Final]
    ... 5 more
Caused by: java.lang.ClassNotFoundException: com.comcast.cats.config.ui.monitoring.reboot.UpTimeMonitor from [Module "deployment.OCATS.war:main" from Service Module Loader]
    at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:190)
    at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:468)
    at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:456)
    at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
    at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:120)
    at org.jboss.as.ejb3.deployment.processors.BusinessViewAnnotationProcessor.getEjbClass(BusinessViewAnnotationProcessor.java:225)
    ... 7 more

15:48:00,439 INFO  [org.jboss.as.server](management-handler-thread - 1) JBAS015870: Deploy of deployment "OCATS.war" was rolled back with failure message {"JBAS014671: Failed services" => {"jboss.deployment.unit.\"OCATS.war\".POST_MODULE" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"OCATS.war\".POST_MODULE: Failed to process phase POST_MODULE of deployment \"OCATS.war\""}}
15:48:00,855 INFO  [org.jboss.as.server.deployment](MSC service thread 1-1) JBAS015877: Stopped deployment OCATS.war in 428ms
15:48:00,865 INFO  [org.jboss.as.controller](management-handler-thread - 1) JBAS014774: Service status report
JBAS014777:   Services which failed to start:      service jboss.deployment.unit."OCATS.war".POST_MODULE: org.jboss.msc.service.StartException in service jboss.deployment.unit."OCATS.war".POST_MODULE: Failed to process phase POST_MODULE of deployment "OCATS.war"

**Comment by sjsauto** [comment]
Any help on this would be highly appreciated, i am currently stuck that this point and not able to proceed further. 

Thanks in advance.
