### ISSUE TITLE
Failed to access the WSDL at: http://192.168.56.101/CATS/DeviceSearchService?wsdl.

### ISSUE THREAD

**Issue by sjsauto** [Comcast/cats#36]
I am getting the following Error while trying to load the CATSVision . 

At this point , I have only connected the STB through Axis encoder, rest of the hardware's are not connected. 

I have also updated the racks.config file to reflect the Axis IP address. 

Caused by: javax.xml.ws.WebServiceException: Failed to access the WSDL at: http://192.168.56.101/CATS/DeviceSearchService?wsdl. It failed with: 
	Server returned HTTP response code: 503 for URL: http://192.168.56.101/CATS/DeviceSearchService?wsdl.
      at com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.tryWithMex(Unknown Source)
      at com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.parse(Unknown Source)
      at com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.parse(Unknown Source)
      at com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.parse(Unknown Source)
      at com.sun.xml.internal.ws.client.WSServiceDelegate.parseWSDL(Unknown Source)
      at com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(Unknown Source)
      at com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(Unknown Source)
      at com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(Unknown Source)
      at com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(Unknown Source)
      at com.sun.xml.internal.ws.spi.ProviderImpl.createServiceDelegate(Unknown Source)
      at javax.xml.ws.Service.<init>(Unknown Source)
      at com.comcast.cats.DeviceSearchServiceEndpoint.<init>(DeviceSearchServiceEndpoint.java:58)
      at com.comcast.cats.domain.service.AbstractService.getDeviceSearchService(AbstractService.java:67)
      at com.comcast.cats.domain.service.SettopDomainServiceImpl.findByMacId(SettopDomainServiceImpl.java:50)
      at com.comcast.cats.SettopFactoryImpl.findSettopByHostMac(SettopFactoryImpl.java:99)
      at com.comcast.cats.vision.panel.videogrid.VideoGridController.createSettops(VideoGridController.java:475)
      at com.comcast.cats.vision.CatsVisionController.createMultiVisionPanel(CatsVisionController.java:560)
      at com.comcast.cats.vision.CatsVisionController.addTabs(CatsVisionController.java:575)
      at com.comcast.cats.vision.CATSVisionApplication.startup(CATSVisionApplication.java:131)
      at org.jdesktop.application.Application$1.run(Application.java:171)
      at java.awt.event.InvocationEvent.dispatch(Unknown Source)
      at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
      at java.awt.EventQueue.access$500(Unknown Source)
      at java.awt.EventQueue$3.run(Unknown Source)
      at java.awt.EventQueue$3.run(Unknown Source)
      at java.security.AccessController.doPrivileged(Native Method)
      at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
      at java.awt.EventQueue.dispatchEvent(Unknown Source)
      at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
      at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
      at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
      at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
      at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
      at java.awt.EventDispatchThread.run(Unknown Source)

![image](https://cloud.githubusercontent.com/assets/22946767/20160618/2f003cfe-a69d-11e6-9fcb-54953bfa8257.png)

I validated the telnet connectivity and its working fine. 

Please suggest if anything else needs to be checked ?

**Comment by sjsauto** [comment]
I am getting the below error message when I click on the recording button. 

ERROR : DIRECTV
Video recorder custom JAX-RS exception handler for [class javax.ejb.EJBTransactionRolledbackException]. java.lang.String cannot be cast to com.comcast.cats.info.VideoRecorderResponse
