### ISSUE TITLE
JBoss started but web access shows 404

### ISSUE THREAD

**Issue by jinzhouus** [Comcast/cats#43]
Hello,

I got the following error in server.log during startup:
[org.jboss.msc.service.fail] (MSC service thread 1-8) MSC00001: Failed to start service jboss.deployment.unit."OCATS.war": org.jboss.msc.service.StartException in service jboss.deployment.unit."OCATS.war": Failed to start service
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1767) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_79]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_79]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_79]
Caused by: java.lang.IllegalStateException: JBAS014922: Directory /opt/ocats/software/jboss/current/standalone/data/content/29 is not writable
        at org.jboss.as.repository.ContentRepository$Factory$ContentRepositoryImpl.validateDir(ContentRepository.java:226) [jboss-as-deployment-repository-7.1.1.Final.jar:7.1.1.Final]

It sounds like a permission issue.  Can someone please give a hint on how to fix it?

**Comment by XsubinX** [comment]
Undeploy all and try to redeploy

**Comment by jinzhouus** [comment]
Thank you for the quick reply!  Problem solved.
